import CssBaseline from "@mui/material/CssBaseline";
import Layout from "@/components/Layout";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import theme from "./theme/theme";
import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material/styles";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "NEXTjs Test | Marah Daher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <ToastContainer position="top-right" autoClose={3000} />
            <Layout>{children}</Layout>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
